#!/bin/zsh

# Shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.dotfiles

# Load everything in this module
for file in $ZSH/*/*.zsh; do
  source "$file"
done

# Load shell wide config
source $HOME/.aliases
source $HOME/.functions

# Loading dircolors
eval `dircolors $HOME/.dircolors`